import { useState } from "react";

// ─── CONSTANTS ────────────────────────────────────────────────────────────────
const STAGE_LABELS = ["","Enquiry","Quote","Underwriting","Repricing","Reinsurer","Fund Transfer","Policy Issue","In-Force"];
const STAGE_COLORS = ["","#388bfd","#388bfd","#b45309","#d4a017","#0f766e","#1d4ed8","#166534","#374151"];
const STAGES = [{n:1,label:"Enquiry"},{n:2,label:"Quote"},{n:3,label:"Underwriting"},{n:4,label:"Repricing"},{n:5,label:"Reinsurer"},{n:6,label:"Fund Transfer"},{n:7,label:"Policy Issue"},{n:8,label:"In-Force"}];
const NAV = ["Dashboard","Cases","Actions","IFA Relationships","Workflow Reference","Integrations"];

// ─── STAGE CHECKLISTS ─────────────────────────────────────────────────────────
const STAGE_CHECKS = {
  1:[{id:"ifa_verified",label:"IFA identity verified via Unipass",critical:true},{id:"ph_details_confirmed",label:"Policyholder details confirmed",critical:true},{id:"annuity_type_confirmed",label:"Annuity type & options confirmed with IFA",critical:true},{id:"enhanced_triage",label:"Enhanced annuity triage completed",critical:false},{id:"quote_requested",label:"Quote requested and logged",critical:true}],
  2:[{id:"quote_generated",label:"Quote generated by pricing engine",critical:true},{id:"quote_sent_ifa",label:"Quote sent to IFA via Mailock",critical:true},{id:"suitability_confirmed",label:"IFA suitability assessment confirmed",critical:true},{id:"ifa_accepted",label:"IFA formally accepted quote",critical:true}],
  3:[{id:"medical_triage",label:"Medical triage completed — conditions coded (ICD-10)",critical:true},{id:"igpr_requested",label:"iGPR GP report request raised",critical:true},{id:"gp_report_received",label:"GP report received and reviewed",critical:true},{id:"morgan_ash",label:"Morgan Ash MARS assessment (if vulnerability flagged)",critical:false},{id:"uw_decision",label:"Underwriting decision made and recorded",critical:true},{id:"chief_uw",label:"Chief UW sign-off (if referred)",critical:false},{id:"art9_confirmed",label:"Art.9 GDPR — medical data stored in isolated system",critical:true}],
  4:[{id:"reprice_triggered",label:"Reprice trigger reason logged",critical:true},{id:"new_rate_calculated",label:"New annuity rate calculated and validated",critical:true},{id:"ifa_notified",label:"IFA notified via Mailock — validity window started",critical:true},{id:"ifa_accepted_reprice",label:"IFA formally accepted repriced terms",critical:true},{id:"reprice_audit",label:"Reprice event audit log confirmed (FCA requirement)",critical:true}],
  5:[{id:"submission_pack",label:"Reinsurer submission pack prepared",critical:true},{id:"medical_bundle",label:"Medical evidence bundle included and verified",critical:true},{id:"sent_to_reinsurer",label:"Submission sent to reinsurer — reference logged",critical:true},{id:"reinsurer_contact",label:"Reinsurer confirmed receipt of submission",critical:true},{id:"decision_received",label:"Reinsurer decision received",critical:true},{id:"counter_offer_reviewed",label:"Counter-offer reviewed by Chief UW (if applicable)",critical:false},{id:"terms_accepted",label:"Final reinsurer terms accepted",critical:true}],
  6:[{id:"transfer_requested",label:"Transfer request sent to ceding provider",critical:true},{id:"origo_tracking",label:"Origo Options tracking reference obtained",critical:true},{id:"funds_received",label:"Funds received in full — amount verified",critical:true},{id:"reconciliation",label:"Bank reconciliation completed — no shortfall",critical:true},{id:"tolerance_check",label:"Tolerance check passed (±£50 threshold)",critical:true}],
  7:[{id:"preissue_checks",label:"Pre-issue checklist completed",critical:true},{id:"policy_schedule",label:"Policy schedule generated",critical:true},{id:"ipid_generated",label:"IPID document generated (FCA requirement)",critical:true},{id:"welcome_letter",label:"Welcome letter generated",critical:true},{id:"docs_sent_ph",label:"Documents sent to policyholder via DocuSign",critical:true},{id:"docs_sent_ifa",label:"Copy sent to IFA back-office",critical:true},{id:"ph_signed",label:"Policyholder signature received",critical:true},{id:"first_payment_set",label:"First payment scheduled in payment engine",critical:true},{id:"consumer_duty",label:"Consumer Duty understanding confirmed",critical:true}],
  8:[{id:"payments_running",label:"Payment run confirmed active",critical:true},{id:"annual_statement",label:"Annual statement sent (FCA requirement)",critical:false},{id:"death_verified",label:"Death verified — cessation/survivor pension actioned (if applicable)",critical:false},{id:"payment_query_resolved",label:"Payment query resolved (if applicable)",critical:false}],
};

// ─── IFA DATA ─────────────────────────────────────────────────────────────────
const ONBOARDING_STAGES = [
  {id:"application",label:"Application Received"},
  {id:"kyc_id",label:"KYC — ID Verified"},
  {id:"kyc_aml",label:"AML Screening"},
  {id:"sanctions",label:"Sanctions Check"},
  {id:"pep_check",label:"PEP Check"},
  {id:"fca_check",label:"FCA Register Verified"},
  {id:"unipass",label:"Unipass / Origo Setup"},
  {id:"agency_agreement",label:"Agency Agreement Signed"},
  {id:"commission_agreed",label:"Commission Terms Agreed"},
  {id:"system_access",label:"Portal Access Granted"},
  {id:"first_case",label:"First Case Submitted"},
];

const INITIAL_IFAS = [
  {
    id:"IFA-001", firm:"Hargreaves Lansdown", type:"National Network",
    fcaNumber:"115248", unipaussId:"HL-UP-44821", status:"Active",
    relationshipManager:"Sarah Ahmed", lastContact:"06/03/2026",
    onboardedDate:"14/01/2022", reviewDueDate:"14/01/2027",
    commissionType:"Indemnity", initialCommission:1.5, trailCommission:0.0,
    paymentTerms:"Monthly", preferredContact:"Mailock",
    totalCasesSubmitted:34, casesCompleted:28, casesPending:4, casesIncomplete:2,
    totalPremium:"£4,812,000", commissionPaid:"£72,180",
    address:"One College Square South, Anchor Road, Bristol, BS1 5HL",
    contact:"annuities@hl.co.uk / 0117 900 9000",
    notes:"Key strategic partner. High volume, good quality submissions. Annual review due Jan 2027.",
    onboardingChecks:{application:true,kyc_id:true,kyc_aml:true,sanctions:true,pep_check:true,fca_check:true,unipass:true,agency_agreement:true,commission_agreed:true,system_access:true,first_case:true},
    sanctions:{screened:true,screenedDate:"12/01/2022",result:"Clear",provider:"ComplyAdvantage",nextReview:"12/01/2027"},
    aml:{verified:true,verifiedDate:"12/01/2022",method:"Electronic verification",documents:["Firm registration","Director ID","Bank letter"],nextReview:"12/01/2027"},
    pep:{checked:true,checkedDate:"12/01/2022",result:"No PEP/RCA identified"},
    commissionHistory:[{date:"28/02/2026",amount:"£3,240",cases:2},{date:"31/01/2026",amount:"£4,860",cases:3},{date:"31/12/2025",amount:"£2,160",cases:1}],
    cases:["ANN-2026-0891","ANN-2025-0741"],
  },
  {
    id:"IFA-002", firm:"St. James's Place", type:"National Network",
    fcaNumber:"176705", unipaussId:"SJP-UP-33412", status:"Active",
    relationshipManager:"James Palmer", lastContact:"04/03/2026",
    onboardedDate:"03/06/2021", reviewDueDate:"03/06/2026",
    commissionType:"Indemnity", initialCommission:1.75, trailCommission:0.0,
    paymentTerms:"Monthly", preferredContact:"Email",
    totalCasesSubmitted:19, casesCompleted:14, casesPending:3, casesIncomplete:2,
    totalPremium:"£2,134,500", commissionPaid:"£37,354",
    address:"St. James's Place House, 1 Tetbury Road, Cirencester, GL7 1FP",
    contact:"annuities@sjp.co.uk / 01285 640302",
    notes:"Review due June 2026. Two recent submissions returned for incomplete medical questionnaires.",
    onboardingChecks:{application:true,kyc_id:true,kyc_aml:true,sanctions:true,pep_check:true,fca_check:true,unipass:true,agency_agreement:true,commission_agreed:true,system_access:true,first_case:true},
    sanctions:{screened:true,screenedDate:"01/06/2021",result:"Clear",provider:"LexisNexis",nextReview:"01/06/2026"},
    aml:{verified:true,verifiedDate:"01/06/2021",method:"Electronic verification",documents:["Firm registration","Director ID"],nextReview:"01/06/2026"},
    pep:{checked:true,checkedDate:"01/06/2021",result:"No PEP/RCA identified"},
    commissionHistory:[{date:"28/02/2026",amount:"£1,750",cases:1},{date:"31/01/2026",amount:"£3,500",cases:2}],
    cases:["ANN-2026-0892","ANN-2026-0887","ANN-2026-0864"],
  },
  {
    id:"IFA-003", firm:"Quilter", type:"National Network",
    fcaNumber:"907783", unipaussId:"QL-UP-55209", status:"Active",
    relationshipManager:"Sarah Ahmed", lastContact:"07/03/2026",
    onboardedDate:"22/09/2020", reviewDueDate:"22/09/2025",
    commissionType:"Fee Offset", initialCommission:1.25, trailCommission:0.0,
    paymentTerms:"Monthly", preferredContact:"Mailock",
    totalCasesSubmitted:41, casesCompleted:35, casesPending:4, casesIncomplete:2,
    totalPremium:"£6,102,000", commissionPaid:"£76,275",
    address:"Senator House, 85 Queen Victoria Street, London, EC4V 4AB",
    contact:"annuities@quilter.com / 020 7618 8000",
    notes:"Largest volume partner. Annual review overdue — chased 07/03/2026. Escalate if no response.",
    onboardingChecks:{application:true,kyc_id:true,kyc_aml:true,sanctions:true,pep_check:true,fca_check:true,unipass:true,agency_agreement:true,commission_agreed:true,system_access:true,first_case:true},
    sanctions:{screened:true,screenedDate:"20/09/2020",result:"Clear",provider:"ComplyAdvantage",nextReview:"20/09/2025"},
    aml:{verified:true,verifiedDate:"20/09/2020",method:"Electronic verification",documents:["Firm registration","Director ID","Source of business"],nextReview:"20/09/2025"},
    pep:{checked:true,checkedDate:"20/09/2020",result:"No PEP/RCA identified"},
    commissionHistory:[{date:"28/02/2026",amount:"£5,100",cases:4},{date:"31/01/2026",amount:"£3,825",cases:3},{date:"31/12/2025",amount:"£2,550",cases:2}],
    cases:["ANN-2026-0895","ANN-2026-0879","ANN-2026-0882","ANN-2025-0698"],
  },
  {
    id:"IFA-004", firm:"Tilney", type:"Regional IFA",
    fcaNumber:"551799", unipaussId:"TL-UP-22108", status:"Active",
    relationshipManager:"Kevin Jones", lastContact:"01/03/2026",
    onboardedDate:"11/03/2023", reviewDueDate:"11/03/2026",
    commissionType:"Indemnity", initialCommission:1.5, trailCommission:0.0,
    paymentTerms:"Monthly", preferredContact:"Mailock",
    totalCasesSubmitted:11, casesCompleted:7, casesPending:3, casesIncomplete:1,
    totalPremium:"£1,442,150", commissionPaid:"£21,632",
    address:"Royal Liver Building, Pier Head, Liverpool, L3 1NY",
    contact:"annuities@tilney.co.uk / 0207 189 2400",
    notes:"Annual review due 11/03/2026 — overdue. Good submission quality generally.",
    onboardingChecks:{application:true,kyc_id:true,kyc_aml:true,sanctions:true,pep_check:true,fca_check:true,unipass:true,agency_agreement:true,commission_agreed:true,system_access:true,first_case:true},
    sanctions:{screened:true,screenedDate:"09/03/2023",result:"Clear",provider:"ComplyAdvantage",nextReview:"09/03/2026"},
    aml:{verified:true,verifiedDate:"09/03/2023",method:"Electronic verification",documents:["Firm registration","Director ID"],nextReview:"09/03/2026"},
    pep:{checked:true,checkedDate:"09/03/2023",result:"No PEP/RCA identified"},
    commissionHistory:[{date:"28/02/2026",amount:"£2,100",cases:1},{date:"31/12/2025",amount:"£1,050",cases:1}],
    cases:["ANN-2026-0898","ANN-2026-0871"],
  },
  {
    id:"IFA-005", firm:"Brewin Dolphin", type:"Regional IFA",
    fcaNumber:"124444", unipaussId:"BD-UP-11934", status:"Active",
    relationshipManager:"James Palmer", lastContact:"08/03/2026",
    onboardedDate:"05/07/2021", reviewDueDate:"05/07/2026",
    commissionType:"Indemnity", initialCommission:1.5, trailCommission:0.0,
    paymentTerms:"Monthly", preferredContact:"Email",
    totalCasesSubmitted:16, casesCompleted:12, casesPending:2, casesIncomplete:2,
    totalPremium:"£1,931,400", commissionPaid:"£28,971",
    address:"12 Smithfield Street, London, EC1A 9LA",
    contact:"annuities@brewin.co.uk / 020 7248 4400",
    notes:"Two current cases with incomplete fund transfer documentation. Follow-up required.",
    onboardingChecks:{application:true,kyc_id:true,kyc_aml:true,sanctions:true,pep_check:true,fca_check:true,unipass:true,agency_agreement:true,commission_agreed:true,system_access:true,first_case:true},
    sanctions:{screened:true,screenedDate:"03/07/2021",result:"Clear",provider:"LexisNexis",nextReview:"03/07/2026"},
    aml:{verified:true,verifiedDate:"03/07/2021",method:"Electronic verification",documents:["Firm registration","Director ID"],nextReview:"03/07/2026"},
    pep:{checked:true,checkedDate:"03/07/2021",result:"No PEP/RCA identified"},
    commissionHistory:[{date:"28/02/2026",amount:"£1,500",cases:1},{date:"31/01/2026",amount:"£3,000",cases:2}],
    cases:["ANN-2026-0885","ANN-2026-0876","ANN-2025-0712"],
  },
  {
    id:"IFA-006", firm:"Rathbones", type:"Regional IFA",
    fcaNumber:"070493", unipaussId:"RB-UP-88341", status:"Active",
    relationshipManager:"Kevin Jones", lastContact:"05/03/2026",
    onboardedDate:"18/11/2019", reviewDueDate:"18/11/2024",
    commissionType:"Indemnity", initialCommission:1.5, trailCommission:0.0,
    paymentTerms:"Monthly", preferredContact:"Mailock",
    totalCasesSubmitted:28, casesCompleted:23, casesPending:3, casesIncomplete:2,
    totalPremium:"£3,812,500", commissionPaid:"£57,188",
    address:"8 Finsbury Circus, London, EC2M 7AZ",
    contact:"annuities@rathbones.com / 020 7399 0000",
    notes:"Annual review significantly overdue (Nov 2024). KYC/AML refresh required. Escalated to Compliance.",
    onboardingChecks:{application:true,kyc_id:true,kyc_aml:true,sanctions:true,pep_check:true,fca_check:true,unipass:true,agency_agreement:true,commission_agreed:true,system_access:true,first_case:true},
    sanctions:{screened:true,screenedDate:"15/11/2019",result:"Clear",provider:"ComplyAdvantage",nextReview:"15/11/2024"},
    aml:{verified:true,verifiedDate:"15/11/2019",method:"Electronic verification",documents:["Firm registration","Director ID","Source of business"],nextReview:"15/11/2024"},
    pep:{checked:true,checkedDate:"15/11/2019",result:"No PEP/RCA identified"},
    commissionHistory:[{date:"28/02/2026",amount:"£1,500",cases:1},{date:"31/01/2026",amount:"£3,000",cases:2},{date:"31/12/2025",amount:"£1,500",cases:1}],
    cases:["ANN-2026-0901","ANN-2026-0881","ANN-2026-0869"],
  },
  {
    id:"IFA-007", firm:"Clarity Wealth Ltd", type:"Independent IFA",
    fcaNumber:"812334", unipaussId:"", status:"Onboarding",
    relationshipManager:"Sarah Ahmed", lastContact:"09/03/2026",
    onboardedDate:"", reviewDueDate:"",
    commissionType:"Indemnity", initialCommission:1.25, trailCommission:0.0,
    paymentTerms:"Monthly", preferredContact:"Email",
    totalCasesSubmitted:0, casesCompleted:0, casesPending:0, casesIncomplete:0,
    totalPremium:"£0", commissionPaid:"£0",
    address:"14 King Street, Manchester, M2 6AG",
    contact:"info@claritywealth.co.uk / 0161 834 5500",
    notes:"New IFA onboarding initiated 01/03/2026. KYC and sanctions in progress. Good pipeline expected.",
    onboardingChecks:{application:true,kyc_id:true,kyc_aml:true,sanctions:false,pep_check:false,fca_check:true,unipass:false,agency_agreement:false,commission_agreed:false,system_access:false,first_case:false},
    sanctions:{screened:false,screenedDate:"",result:"In progress",provider:"ComplyAdvantage",nextReview:""},
    aml:{verified:true,verifiedDate:"05/03/2026",method:"Electronic verification",documents:["Firm registration","Director ID"],nextReview:""},
    pep:{checked:false,checkedDate:"",result:"Pending"},
    commissionHistory:[],
    cases:[],
  },
  {
    id:"IFA-008", firm:"Meridian Financial Planning", type:"Independent IFA",
    fcaNumber:"934112", unipaussId:"", status:"Suspended",
    relationshipManager:"James Palmer", lastContact:"15/01/2026",
    onboardedDate:"04/04/2022", reviewDueDate:"04/04/2025",
    commissionType:"Indemnity", initialCommission:1.5, trailCommission:0.0,
    paymentTerms:"Monthly", preferredContact:"Email",
    totalCasesSubmitted:6, casesCompleted:3, casesPending:0, casesIncomplete:3,
    totalPremium:"£498,000", commissionPaid:"£7,470",
    address:"22 High Street, Leeds, LS1 4HR",
    contact:"admin@meridianfp.co.uk / 0113 245 8800",
    notes:"Suspended pending compliance investigation — three cases rejected for falsified medical questionnaires. Compliance team notified. Do not accept new cases.",
    onboardingChecks:{application:true,kyc_id:true,kyc_aml:true,sanctions:true,pep_check:true,fca_check:true,unipass:true,agency_agreement:true,commission_agreed:true,system_access:false,first_case:true},
    sanctions:{screened:true,screenedDate:"02/04/2022",result:"Clear — REVIEW REQUIRED",provider:"LexisNexis",nextReview:"04/04/2025"},
    aml:{verified:true,verifiedDate:"02/04/2022",method:"Electronic verification",documents:["Firm registration"],nextReview:"04/04/2025"},
    pep:{checked:true,checkedDate:"02/04/2022",result:"No PEP/RCA identified"},
    commissionHistory:[{date:"30/11/2025",amount:"£1,500",cases:1}],
    cases:[],
  },
];

// ─── CASE DATA ────────────────────────────────────────────────────────────────
const INITIAL_CASES = [
  {id:"ANN-2026-0901",name:"James Whitfield",age:61,fund:"£98,400",stage:1,urgent:false,ifa:"Rathbones",ifaId:"IFA-006",days:1,annuityType:"Level — Single Life",dob:"14/03/1964",gender:"Male",smoker:"Non-smoker",postcode:"SK4 2NL",paymentFreq:"Monthly",guaranteePeriod:"5 years",niNumber:"JW421836C",address:"12 Maple Avenue, Stockport, SK4 2NL",contact:"07812 334 556 / j.whitfield@email.co.uk",notes:"Straightforward level single life — no medical flags at enquiry stage."},
  {id:"ANN-2026-0898",name:"Helen Forsythe",age:66,fund:"£176,250",stage:1,urgent:false,ifa:"Tilney",ifaId:"IFA-004",days:2,annuityType:"Escalating 3% — Joint Life",dob:"22/07/1959",gender:"Female",smoker:"Non-smoker",postcode:"OX2 6QA",paymentFreq:"Monthly",guaranteePeriod:"10 years",niNumber:"HF882341B",address:"4 Blenheim Close, Oxford, OX2 6QA",contact:"07723 441 882 / helen.forsythe@outlook.com",notes:"Joint life — partner details required."},
  {id:"ANN-2026-0895",name:"Susan Fairweather",age:63,fund:"£310,000",stage:2,urgent:false,ifa:"Quilter",ifaId:"IFA-003",days:1,annuityType:"Level — Joint Life",dob:"05/11/1962",gender:"Female",smoker:"Non-smoker",postcode:"BS8 1TH",paymentFreq:"Monthly",guaranteePeriod:"None",niNumber:"SF334821A",address:"7 Clifton Park Road, Bristol, BS8 1TH",contact:"07934 112 774 / s.fairweather@gmail.com",quoteRate:"5.12% p.a.",quoteAnnualIncome:"£15,872",quoteExpiry:"14 Mar 2026",notes:"Large fund — facultative reinsurance required."},
  {id:"ANN-2026-0892",name:"Thomas Briggs",age:69,fund:"£54,100",stage:2,urgent:false,ifa:"St. James's Place",ifaId:"IFA-002",days:3,annuityType:"Level — Single Life",dob:"30/09/1956",gender:"Male",smoker:"Ex-smoker",postcode:"NG1 4AB",paymentFreq:"Quarterly",guaranteePeriod:"5 years",niNumber:"TB774412D",address:"22 Castle Gate, Nottingham, NG1 4AB",contact:"07541 223 990 / tbriggs@btinternet.com",quoteRate:"5.76% p.a.",quoteAnnualIncome:"£3,116",quoteExpiry:"16 Mar 2026",notes:"Ex-smoker flagged — potential enhanced rate."},
  {id:"ANN-2026-0891",name:"Margaret Thornton",age:67,fund:"£142,500",stage:3,urgent:true,ifa:"Hargreaves Lansdown",ifaId:"IFA-001",days:4,annuityType:"Enhanced — Joint Life",dob:"18/04/1958",gender:"Female",smoker:"Non-smoker",postcode:"LS6 2EP",paymentFreq:"Monthly",guaranteePeriod:"5 years",niNumber:"MT221934B",address:"8 Headingley Lane, Leeds, LS6 2EP",contact:"07812 556 334 / m.thornton@yahoo.co.uk",conditions:"Type 2 Diabetes, Hypertension",medications:"Metformin 500mg, Amlodipine 5mg",gp:"Thornton Medical Centre, Leeds",igprRef:"Awaiting",uwDecision:"Pending",notes:"Two qualifying conditions — automatic refer to medical underwriting."},
  {id:"ANN-2026-0885",name:"Colin Draper",age:71,fund:"£88,750",stage:3,urgent:true,ifa:"Brewin Dolphin",ifaId:"IFA-005",days:9,annuityType:"Enhanced — Single Life",dob:"02/12/1954",gender:"Male",smoker:"Ex-smoker",postcode:"M20 3LB",paymentFreq:"Monthly",guaranteePeriod:"None",niNumber:"CD881243A",address:"31 Palatine Road, Manchester, M20 3LB",contact:"07634 882 113 / c.draper@hotmail.com",conditions:"COPD, Type 2 Diabetes, Obesity (BMI 34)",medications:"Salbutamol, Metformin 1g, Atorvastatin 20mg",gp:"Palatine Road Surgery, Manchester",igprRef:"IGPR-2026-44821",uwDecision:"Under Review — Chief UW Referral Likely",notes:"3 conditions present. Chief UW referral being prepared."},
  {id:"ANN-2026-0881",name:"Dorothy Ashworth",age:74,fund:"£201,000",stage:3,urgent:true,ifa:"Rathbones",ifaId:"IFA-006",days:14,annuityType:"Enhanced — Single Life",dob:"11/06/1951",gender:"Female",smoker:"Non-smoker",postcode:"W1G 8QN",paymentFreq:"Monthly",guaranteePeriod:"None",niNumber:"DA334512C",address:"14 Harley Street, London, W1G 8QN",contact:"07201 445 771 / d.ashworth@gmail.com",conditions:"Stroke (2022), Atrial Fibrillation, Hypertension",medications:"Warfarin, Bisoprolol 5mg, Ramipril 10mg",gp:"Marylebone Health Centre, London",igprRef:"IGPR-2026-44103",morganAshRef:"MARS-2026-0882",uwDecision:"Referred to Chief UW",notes:"Complex medical history. Morgan Ash vulnerability triggered."},
  {id:"ANN-2026-0887",name:"Robert Hesketh",age:72,fund:"£89,200",stage:4,urgent:true,ifa:"St. James's Place",ifaId:"IFA-002",days:2,annuityType:"Level — Single Life",dob:"14/08/1953",gender:"Male",smoker:"Non-smoker",postcode:"CH1 2LR",paymentFreq:"Monthly",guaranteePeriod:"5 years",niNumber:"RH441823D",address:"5 Eastgate Row, Chester, CH1 2LR",contact:"07712 334 009 / r.hesketh@btinternet.com",repriceReason:"Medical evidence — enhanced rate applied",newRate:"5.84% p.a.",previousRate:"5.66% p.a.",rateChange:"+0.18%",validityExpiry:"13 Mar 2026",notes:"Validity window closes in 2 days."},
  {id:"ANN-2026-0879",name:"Anne-Marie Gallagher",age:65,fund:"£134,800",stage:4,urgent:false,ifa:"Quilter",ifaId:"IFA-003",days:5,annuityType:"Escalating 3% — Joint Life",dob:"27/02/1961",gender:"Female",smoker:"Non-smoker",postcode:"L1 8JQ",paymentFreq:"Monthly",guaranteePeriod:"10 years",niNumber:"AG112344B",address:"88 Bold Street, Liverpool, L1 8JQ",contact:"07823 556 221 / amgallagher@gmail.com",repriceReason:"Fund value changed — CETV uplift",newRate:"4.92% p.a.",previousRate:"4.88% p.a.",rateChange:"+0.04%",validityExpiry:"17 Mar 2026",notes:"CETV increased on recalculation."},
  {id:"ANN-2026-0882",name:"Patricia Walmsley",age:65,fund:"£214,000",stage:5,urgent:false,ifa:"Quilter",ifaId:"IFA-003",days:12,annuityType:"Enhanced — Single Life",dob:"09/01/1961",gender:"Female",smoker:"Non-smoker",postcode:"YO1 9RY",paymentFreq:"Monthly",guaranteePeriod:"5 years",niNumber:"PW334112A",address:"3 The Shambles, York, YO1 9RY",contact:"07934 221 445 / p.walmsley@outlook.com",reinsurer:"Munich Re",treatyRef:"MR-2026-4421",sumReinsured:"£214,000",submissionDate:"25 Feb 2026",counterOffer:"None",notes:"Facultative submission — awaiting Munich Re decision."},
  {id:"ANN-2026-0875",name:"Frederick Nolan",age:70,fund:"£289,500",stage:5,urgent:true,ifa:"Hargreaves Lansdown",ifaId:"IFA-001",days:22,annuityType:"Enhanced — Joint Life",dob:"04/05/1955",gender:"Male",smoker:"Ex-smoker",postcode:"EH2 4RJ",paymentFreq:"Monthly",guaranteePeriod:"None",niNumber:"FN221834C",address:"21 George Street, Edinburgh, EH2 4RJ",contact:"07612 334 887 / f.nolan@gmail.com",reinsurer:"RGA UK",treatyRef:"RGA-2026-1182",sumReinsured:"£289,500",submissionDate:"15 Feb 2026",counterOffer:"RGA accepting at +15% loading. Chief UW review required.",notes:"Counter-offer requires Chief UW acceptance."},
  {id:"ANN-2026-0876",name:"David Cartwright",age:70,fund:"£67,400",stage:6,urgent:false,ifa:"Brewin Dolphin",ifaId:"IFA-005",days:8,annuityType:"Escalating 3% — Joint Life",dob:"19/10/1955",gender:"Male",smoker:"Non-smoker",postcode:"B1 2JB",paymentFreq:"Monthly",guaranteePeriod:"5 years",niNumber:"DC441823B",address:"7 Colmore Row, Birmingham, B1 2JB",contact:"07534 221 009 / d.cartwright@hotmail.com",cedingProvider:"Legal & General Workplace Pension",expectedTransfer:"£67,400",receivedAmount:"£62,800",origoRef:"ORG-2026-88421",reconciled:"No — shortfall £4,600",notes:"Partial transfer. Second tranche expected 14/03."},
  {id:"ANN-2026-0871",name:"Irene Blackwood",age:68,fund:"£115,900",stage:6,urgent:true,ifa:"Tilney",ifaId:"IFA-004",days:18,annuityType:"Level — Single Life",dob:"30/06/1957",gender:"Female",smoker:"Non-smoker",postcode:"CF10 1EP",paymentFreq:"Monthly",guaranteePeriod:"10 years",niNumber:"IB882341D",address:"14 Park Place, Cardiff, CF10 1EP",contact:"07923 441 556 / i.blackwood@yahoo.co.uk",cedingProvider:"Aviva Pension (Occupational)",expectedTransfer:"£115,900",receivedAmount:"£0",origoRef:"ORG-2026-87334",reconciled:"No — nothing received",notes:"30-day lapse warning in 12 days."},
  {id:"ANN-2026-0869",name:"Gerald Morrison",age:74,fund:"£128,750",stage:7,urgent:false,ifa:"Rathbones",ifaId:"IFA-006",days:3,annuityType:"Enhanced — Single Life",dob:"22/02/1952",gender:"Male",smoker:"Ex-smoker",postcode:"SO14 1AR",paymentFreq:"Monthly",guaranteePeriod:"None",niNumber:"GM334112A",address:"3 Oxford Street, Southampton, SO14 1AR",contact:"07812 334 991 / g.morrison@btinternet.com",policyNumber:"POL-2026-00412",commencementDate:"01 Apr 2026",firstPaymentDate:"30 Apr 2026",annualIncome:"£8,142",coolingOffExpiry:"01 May 2026",ifaCommission:"£1,931.25",notes:"Documents sent to policyholder via DocuSign."},
  {id:"ANN-2026-0864",name:"Vera Hutchinson",age:66,fund:"£93,200",stage:7,urgent:false,ifa:"St. James's Place",ifaId:"IFA-002",days:6,annuityType:"Level — Joint Life",dob:"08/09/1959",gender:"Female",smoker:"Non-smoker",postcode:"NE1 7RU",paymentFreq:"Monthly",guaranteePeriod:"5 years",niNumber:"VH221934C",address:"9 Grey Street, Newcastle, NE1 7RU",contact:"07723 556 334 / v.hutchinson@gmail.com",policyNumber:"POL-2026-00398",commencementDate:"01 Mar 2026",firstPaymentDate:"31 Mar 2026",annualIncome:"£5,124",coolingOffExpiry:"31 Mar 2026",ifaCommission:"£1,398.00",notes:"Policy live. Cooling off expires 31 Mar."},
  {id:"ANN-2025-0741",name:"Arthur Pemberton",age:77,fund:"£104,300",stage:8,urgent:false,ifa:"Hargreaves Lansdown",ifaId:"IFA-001",days:284,annuityType:"Level — Single Life",dob:"14/01/1949",gender:"Male",smoker:"Non-smoker",postcode:"GL50 1BN",paymentFreq:"Monthly",guaranteePeriod:"10 years",niNumber:"AP441823B",address:"2 Montpellier Walk, Cheltenham, GL50 1BN",contact:"07512 334 009 / a.pemberton@btinternet.com",policyNumber:"POL-2025-00284",commencementDate:"01 Jun 2025",annualIncome:"£6,258",lastPaymentDate:"28 Feb 2026",nextPaymentDate:"31 Mar 2026",notes:"Payments running normally."},
  {id:"ANN-2025-0698",name:"Constance Weatherby",age:73,fund:"£187,500",stage:8,urgent:true,ifa:"Quilter",ifaId:"IFA-003",days:412,annuityType:"Enhanced — Joint Life",dob:"03/04/1952",gender:"Female",smoker:"Non-smoker",postcode:"TN1 1HR",paymentFreq:"Monthly",guaranteePeriod:"None",niNumber:"CW882341A",address:"15 Mount Ephraim, Tunbridge Wells, TN1 1HR",contact:"07923 441 112 / estate@weatherby.co.uk",policyNumber:"POL-2025-00201",commencementDate:"01 Jan 2025",annualIncome:"£9,882",lastPaymentDate:"28 Feb 2026",nextPaymentDate:"31 Mar 2026",notes:"Primary life deceased 01/03/2026. Survivor pension (50%) active."},
  {id:"ANN-2025-0712",name:"Norman Blackhurst",age:80,fund:"£72,400",stage:8,urgent:true,ifa:"Brewin Dolphin",ifaId:"IFA-005",days:341,annuityType:"Level — Single Life",dob:"17/07/1945",gender:"Male",smoker:"Non-smoker",postcode:"PR1 2LL",paymentFreq:"Monthly",guaranteePeriod:"5 years",niNumber:"NB334512D",address:"6 Fishergate, Preston, PR1 2LL",contact:"07634 221 009 / n.blackhurst@hotmail.com",policyNumber:"POL-2025-00241",commencementDate:"01 Apr 2025",annualIncome:"£4,320",lastPaymentDate:"Returned — bank details changed",nextPaymentDate:"31 Mar 2026",notes:"February payment returned. New bank details required urgently."},
];

function buildInitialChecks() {
  const s={};
  INITIAL_CASES.forEach(c=>{s[c.id]={};(STAGE_CHECKS[c.stage]||[]).forEach(ch=>{s[c.id][ch.id]=false;});});
  return s;
}

function buildInitialAudit() {
  return {
    "ANN-2026-0891":[{ts:"05/03/2026 09:14",user:"J. Palmer (UW)",action:"iGPR request raised for Margaret Thornton"}],
    "ANN-2026-0875":[{ts:"15/02/2026 11:30",user:"S. Ahmed (UW)",action:"Submission sent to RGA UK — ref RGA-2026-1182"},{ts:"07/03/2026 14:22",user:"S. Ahmed (UW)",action:"Counter-offer received from RGA — loading +15%"}],
    "ANN-2025-0698":[{ts:"01/03/2026 16:45",user:"System",action:"Death notification received via DWP Tell Us Once"},{ts:"02/03/2026 09:00",user:"K. Jones (Ops)",action:"Survivor pension activated at 50% — £411.75/month"}],
  };
}

// ─── ROOT ─────────────────────────────────────────────────────────────────────
export default function AnnuityPortal() {
  const [nav, setNav] = useState("Dashboard");
  const [cases, setCases] = useState(INITIAL_CASES);
  const [ifas, setIfas] = useState(INITIAL_IFAS);
  const [checks, setChecks] = useState(buildInitialChecks);
  const [audit, setAudit] = useState(buildInitialAudit);
  const [selectedCase, setSelectedCase] = useState(null);
  const [selectedIfa, setSelectedIfa] = useState(null);
  const [stageFilter, setStageFilter] = useState(null);
  const [toast, setToast] = useState(null);

  const sc = selectedCase ? cases.find(c=>c.id===selectedCase) : null;
  const si = selectedIfa ? ifas.find(i=>i.id===selectedIfa) : null;

  function showToast(msg,type="success"){setToast({msg,type});setTimeout(()=>setToast(null),3500);}

  function toggleCheck(caseId,checkId){setChecks(p=>({...p,[caseId]:{...p[caseId],[checkId]:!p[caseId][checkId]}}))}

  function advanceStage(caseId){
    const c=cases.find(x=>x.id===caseId); if(!c||c.stage>=8) return;
    const ns=c.stage+1, nc={};
    (STAGE_CHECKS[ns]||[]).forEach(ch=>{nc[ch.id]=false;});
    setCases(p=>p.map(x=>x.id===caseId?{...x,stage:ns}:x));
    setChecks(p=>({...p,[caseId]:nc}));
    const ts=new Date().toLocaleDateString("en-GB")+" "+new Date().toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"});
    setAudit(p=>({...p,[caseId]:[...(p[caseId]||[]),{ts,user:"Current User",action:`Case advanced: ${STAGE_LABELS[c.stage]} → ${STAGE_LABELS[ns]}`}]}));
    showToast(`${c.name} advanced to Stage ${ns}: ${STAGE_LABELS[ns]}`);
  }

  function toggleOnboardingCheck(ifaId,checkId){
    setIfas(p=>p.map(i=>i.id===ifaId?{...i,onboardingChecks:{...i.onboardingChecks,[checkId]:!i.onboardingChecks[checkId]}}:i));
  }

  function getCheckProgress(caseId,stage){
    const sc=STAGE_CHECKS[stage]||[], cc=checks[caseId]||{};
    const crit=sc.filter(c=>c.critical), done=sc.filter(c=>cc[c.id]).length, cd=crit.filter(c=>cc[c.id]).length;
    return {done,total:sc.length,criticalDone:cd,criticalTotal:crit.length,allCriticalDone:cd===crit.length&&crit.length>0,pct:sc.length?Math.round((done/sc.length)*100):0};
  }

  const allActions=cases.flatMap(c=>{
    const cc=checks[c.id]||{};
    return (STAGE_CHECKS[c.stage]||[]).filter(ch=>!cc[ch.id]).map(ch=>({caseId:c.id,caseName:c.name,stage:c.stage,checkId:ch.id,label:ch.label,critical:ch.critical,urgent:c.urgent,ifa:c.ifa,fund:c.fund}));
  });

  const filteredCases=stageFilter?cases.filter(c=>c.stage===stageFilter):cases;

  return (
    <div style={{display:"flex",height:"100vh",background:"#0d1117",fontFamily:"'Palatino Linotype','Book Antiqua',Palatino,Georgia,serif",color:"#c9d1d9",overflow:"hidden"}}>
      {toast&&<div style={{position:"fixed",top:20,right:24,zIndex:1000,background:toast.type==="success"?"#0d2a17":"#2a0d0d",border:`1px solid ${toast.type==="success"?"#3fb950":"#f85149"}`,borderRadius:8,padding:"13px 20px",fontSize:13,color:"#e6edf3",boxShadow:"0 4px 24px #00000099",maxWidth:360}}>{toast.type==="success"?"✓ ":"⚠ "}{toast.msg}</div>}

      {/* Sidebar */}
      <div style={{width:220,background:"#0a0e15",borderRight:"1px solid #161b22",display:"flex",flexDirection:"column",flexShrink:0}}>
        <div style={{padding:"24px 20px 20px",borderBottom:"1px solid #161b22"}}>
          <div style={{fontSize:10,letterSpacing:"0.25em",textTransform:"uppercase",color:"#4a6fa5",marginBottom:4}}>Annuity Operations</div>
          <div style={{fontSize:16,fontWeight:700,color:"#e6edf3"}}>PolicyFlow</div>
          <div style={{fontSize:10,color:"#30363d",marginTop:2}}>v0.4 — IFA Module</div>
        </div>
        <nav style={{padding:"16px 0",flex:1}}>
          {NAV.map(n=>(
            <div key={n} onClick={()=>{setNav(n);setSelectedCase(null);setSelectedIfa(null);setStageFilter(null);}}
              style={{padding:"10px 20px",fontSize:13,cursor:"pointer",display:"flex",alignItems:"center",gap:10,color:nav===n?"#e6edf3":"#6e7681",background:nav===n?"#161b22":"transparent",borderLeft:nav===n?"2px solid #d4a017":"2px solid transparent"}}>
              <span>{["⬡","⬜","◎","◈","◈","⬢"][NAV.indexOf(n)]}</span>{n}
              {n==="Actions"&&allActions.filter(a=>a.critical).length>0&&<span style={{marginLeft:"auto",background:"#f8514922",border:"1px solid #f85149",color:"#f85149",borderRadius:10,padding:"1px 6px",fontSize:10}}>{allActions.filter(a=>a.critical).length}</span>}
              {n==="IFA Relationships"&&ifas.filter(i=>i.status==="Suspended"||i.status==="Onboarding").length>0&&<span style={{marginLeft:"auto",background:"#d4a01722",border:"1px solid #d4a017",color:"#d4a017",borderRadius:10,padding:"1px 6px",fontSize:10}}>{ifas.filter(i=>i.status==="Suspended"||i.status==="Onboarding").length}</span>}
            </div>
          ))}
        </nav>
        <div style={{padding:"16px 20px",borderTop:"1px solid #161b22"}}>
          <div style={{fontSize:11,color:"#4a6fa5"}}>Logged in as</div>
          <div style={{fontSize:12,color:"#8b949e",marginTop:2}}>Senior Underwriter</div>
          <div style={{marginTop:8,display:"inline-block",background:"#162032",border:"1px solid #1f6feb",borderRadius:4,padding:"2px 8px",fontSize:10,color:"#58a6ff"}}>FCA Authorised</div>
        </div>
      </div>

      {/* Main */}
      <div style={{flex:1,display:"flex",flexDirection:"column",overflow:"hidden"}}>
        <div style={{borderBottom:"1px solid #161b22",padding:"14px 28px",display:"flex",justifyContent:"space-between",alignItems:"center",background:"#0d1117",flexShrink:0}}>
          <div>
            <div style={{fontSize:18,fontWeight:700,color:"#e6edf3"}}>{selectedCase?sc?.id:selectedIfa?si?.firm:nav}</div>
            {selectedCase&&sc&&<div style={{fontSize:12,color:"#6e7681",marginTop:1}}>{sc.name} — {sc.annuityType}</div>}
            {selectedIfa&&si&&<div style={{fontSize:12,color:"#6e7681",marginTop:1}}>{si.type} — FCA {si.fcaNumber}</div>}
          </div>
          <div style={{display:"flex",gap:10}}>
            <div style={{background:"#161b22",border:"1px solid #30363d",borderRadius:6,padding:"6px 14px",fontSize:12,color:"#8b949e"}}>Mon 9 Mar 2026</div>
            {(selectedCase||selectedIfa)&&<button onClick={()=>{setSelectedCase(null);setSelectedIfa(null);}} style={{background:"transparent",border:"1px solid #30363d",color:"#8b949e",borderRadius:6,padding:"6px 14px",fontSize:12,cursor:"pointer"}}>← Back</button>}
          </div>
        </div>

        <div style={{flex:1,overflowY:"auto",padding:28}}>
          {nav==="Dashboard"&&!selectedCase&&<Dashboard cases={cases} ifas={ifas} getCheckProgress={getCheckProgress} onSelectCase={id=>{setSelectedCase(id);setNav("Cases");}} onSelectStage={s=>{setStageFilter(s);setNav("Cases");}} />}
          {nav==="Cases"&&!selectedCase&&<>
            <div style={{display:"flex",gap:8,marginBottom:16,flexWrap:"wrap"}}>
              <FilterBtn active={!stageFilter} onClick={()=>setStageFilter(null)} label={`All (${cases.length})`} color="#e6edf3" />
              {STAGES.map(s=>{const cnt=cases.filter(c=>c.stage===s.n).length;if(!cnt)return null;return <FilterBtn key={s.n} active={stageFilter===s.n} onClick={()=>setStageFilter(stageFilter===s.n?null:s.n)} label={`${s.label} (${cnt})`} color={STAGE_COLORS[s.n]} />;})}
            </div>
            <CaseTable cases={filteredCases} getCheckProgress={getCheckProgress} onSelect={id=>setSelectedCase(id)} />
          </>}
          {selectedCase&&sc&&<CaseDetail c={sc} checks={checks[sc.id]||{}} audit={audit[sc.id]||[]} getCheckProgress={getCheckProgress} onToggleCheck={chId=>toggleCheck(sc.id,chId)} onAdvance={()=>advanceStage(sc.id)} />}
          {nav==="Actions"&&!selectedCase&&<ActionsView allActions={allActions} onToggleCheck={(cId,chId)=>toggleCheck(cId,chId)} onGoToCase={id=>{setSelectedCase(id);setNav("Cases");}} />}
          {nav==="IFA Relationships"&&!selectedIfa&&<IFAList ifas={ifas} cases={cases} onSelect={id=>setSelectedIfa(id)} />}
          {nav==="IFA Relationships"&&selectedIfa&&si&&<IFADetail ifa={si} cases={cases.filter(c=>c.ifaId===si.id)} onToggleCheck={(chId)=>toggleOnboardingCheck(si.id,chId)} showToast={showToast} />}
          {nav==="Workflow Reference"&&<WorkflowRef />}
          {nav==="Integrations"&&<IntegrationsView />}
        </div>
      </div>
    </div>
  );
}

// ─── DASHBOARD ────────────────────────────────────────────────────────────────
function Dashboard({cases,ifas,getCheckProgress,onSelectCase,onSelectStage}){
  const urgent=cases.filter(c=>c.urgent).length;
  const overdueiFA=ifas.filter(i=>i.status==="Active"&&i.reviewDueDate&&new Date(i.reviewDueDate.split("/").reverse().join("-"))<new Date()).length;
  return(<>
    <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:16,marginBottom:28}}>
      {[{label:"Active Cases",value:cases.length,delta:`${urgent} urgent`,bad:urgent>0},{label:"Awaiting Medical",value:cases.filter(c=>c.stage===3).length,delta:"1 past SLA",bad:true},{label:"IFA Partners",value:ifas.filter(i=>i.status==="Active").length,delta:`${ifas.filter(i=>i.status==="Onboarding").length} onboarding · ${ifas.filter(i=>i.status==="Suspended").length} suspended`,bad:false},{label:"IFA Reviews Overdue",value:overdueiFA,delta:"KYC/AML refresh required",bad:overdueiFA>0}].map(s=>(
        <div key={s.label} style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,padding:"18px 20px"}}>
          <div style={{fontSize:11,color:"#6e7681",letterSpacing:"0.1em",textTransform:"uppercase",marginBottom:8}}>{s.label}</div>
          <div style={{fontSize:32,fontWeight:700,color:"#e6edf3"}}>{s.value}</div>
          <div style={{fontSize:11,marginTop:4,color:s.bad?"#f85149":"#3fb950"}}>{s.delta}</div>
        </div>
      ))}
    </div>
    <div style={{marginBottom:24}}>
      <div style={{fontSize:11,letterSpacing:"0.2em",textTransform:"uppercase",color:"#4a6fa5",marginBottom:12}}>Pipeline by Stage</div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(8,1fr)",gap:8}}>
        {STAGES.map(s=>{
          const sc=cases.filter(c=>c.stage===s.n);
          const avg=sc.length?Math.round(sc.reduce((sum,c)=>sum+getCheckProgress(c.id,s.n).pct,0)/sc.length):0;
          return(<div key={s.n} onClick={()=>onSelectStage(s.n)} style={{background:"#0a0e15",border:`1px solid ${STAGE_COLORS[s.n]}33`,borderRadius:8,padding:"14px 10px",textAlign:"center",cursor:"pointer"}} onMouseEnter={e=>e.currentTarget.style.borderColor=STAGE_COLORS[s.n]} onMouseLeave={e=>e.currentTarget.style.borderColor=STAGE_COLORS[s.n]+"33"}>
            <div style={{fontSize:24,fontWeight:700,color:STAGE_COLORS[s.n]}}>{sc.length}</div>
            <div style={{fontSize:9,color:"#6e7681",marginTop:3}}>{s.label}</div>
            {sc.length>0&&<><div style={{marginTop:8,background:"#161b22",borderRadius:3,height:3}}><div style={{width:`${avg}%`,height:3,background:STAGE_COLORS[s.n],borderRadius:3}}/></div><div style={{fontSize:8,color:"#484f58",marginTop:3}}>{avg}% checks</div></>}
          </div>);
        })}
      </div>
    </div>
    <div style={{fontSize:11,letterSpacing:"0.2em",textTransform:"uppercase",color:"#f85149",marginBottom:12}}>Urgent Cases</div>
    <CaseTable cases={cases.filter(c=>c.urgent)} getCheckProgress={getCheckProgress} onSelect={onSelectCase} />
  </>);
}

// ─── CASE TABLE ───────────────────────────────────────────────────────────────
function CaseTable({cases,getCheckProgress,onSelect}){
  return(<div style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,overflow:"hidden"}}>
    <table style={{width:"100%",borderCollapse:"collapse"}}>
      <thead><tr style={{borderBottom:"1px solid #161b22"}}>{["Case ID","Policyholder","Fund","Stage","Checks","IFA","Days",""].map(h=><th key={h} style={{padding:"10px 14px",textAlign:"left",fontSize:10,letterSpacing:"0.15em",textTransform:"uppercase",color:"#4a6fa5",fontWeight:600}}>{h}</th>)}</tr></thead>
      <tbody>{cases.map((c,i)=>{
        const p=getCheckProgress(c.id,c.stage);
        return(<tr key={c.id} onClick={()=>onSelect(c.id)} style={{borderBottom:"1px solid #0d1117",cursor:"pointer",background:i%2===0?"transparent":"#0b0f16"}} onMouseEnter={e=>e.currentTarget.style.background="#161b22"} onMouseLeave={e=>e.currentTarget.style.background=i%2===0?"transparent":"#0b0f16"}>
          <td style={{padding:"11px 14px",fontSize:11,color:"#58a6ff",fontFamily:"monospace"}}>{c.id}</td>
          <td style={{padding:"11px 14px"}}><div style={{fontSize:13,color:"#e6edf3"}}>{c.name}</div><div style={{fontSize:10,color:"#6e7681"}}>Age {c.age}</div></td>
          <td style={{padding:"11px 14px",fontSize:13,color:"#d4a017"}}>{c.fund}</td>
          <td style={{padding:"11px 14px"}}><StageBadge stage={c.stage}/></td>
          <td style={{padding:"11px 14px",minWidth:110}}>
            <div style={{background:"#161b22",borderRadius:3,height:4,marginBottom:4}}><div style={{width:`${p.pct}%`,height:4,background:p.allCriticalDone?"#3fb950":STAGE_COLORS[c.stage],borderRadius:3,transition:"width 0.3s"}}/></div>
            <div style={{fontSize:10,color:p.allCriticalDone?"#3fb950":"#6e7681"}}>{p.done}/{p.total}{p.allCriticalDone?" ✓":""}</div>
          </td>
          <td style={{padding:"11px 14px",fontSize:11,color:"#6e7681"}}>{c.ifa}</td>
          <td style={{padding:"11px 14px",fontSize:12,color:c.urgent?"#f85149":"#8b949e"}}>{c.days}d {c.urgent&&"⚠"}</td>
          <td style={{padding:"11px 14px",fontSize:12,color:"#4a6fa5"}}>→</td>
        </tr>);
      })}</tbody>
    </table>
  </div>);
}

// ─── CASE DETAIL ──────────────────────────────────────────────────────────────
function CaseDetail({c,checks,audit,getCheckProgress,onToggleCheck,onAdvance}){
  const [tab,setTab]=useState("checklist");
  const sc=STAGE_CHECKS[c.stage]||[], p=getCheckProgress(c.id,c.stage), canAdvance=p.allCriticalDone&&c.stage<8;
  return(<div><style>{`@keyframes fadeUp{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}`}</style>
    <div style={{animation:"fadeUp 0.2s ease"}}>
      <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14,marginBottom:20}}>
        {[{l:"Fund Value",v:c.fund},{l:"Annuity Type",v:c.annuityType},{l:"IFA / Broker",v:c.ifa},{l:"Stage",v:`${c.stage}. ${STAGE_LABELS[c.stage]}`}].map(item=>(
          <div key={item.l} style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:8,padding:"14px 16px"}}>
            <div style={{fontSize:10,letterSpacing:"0.15em",color:"#4a6fa5",textTransform:"uppercase",marginBottom:4}}>{item.l}</div>
            <div style={{fontSize:14,color:"#e6edf3",fontWeight:600}}>{item.v}</div>
          </div>
        ))}
      </div>
      <div style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,padding:"16px 20px",marginBottom:18}}>
        <div style={{display:"flex",alignItems:"center"}}>
          {STAGES.map((s,i)=>{const done=s.n<c.stage,active=s.n===c.stage,col=done?"#3fb950":active?"#d4a017":"#21262d",tcol=done?"#3fb950":active?"#d4a017":"#484f58";return(<div key={s.n} style={{display:"flex",alignItems:"center",flex:1}}>
            <div style={{display:"flex",flexDirection:"column",alignItems:"center",minWidth:50}}>
              <div style={{width:26,height:26,borderRadius:"50%",background:active?"#d4a01722":done?"#3fb95022":"#161b22",border:`2px solid ${col}`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,fontWeight:700,color:tcol}}>{done?"✓":s.n}</div>
              <div style={{fontSize:8,color:tcol,marginTop:3,textAlign:"center"}}>{s.label}</div>
            </div>
            {i<STAGES.length-1&&<div style={{flex:1,height:2,background:done?"#3fb950":"#21262d",margin:"0 2px",marginBottom:14}}/>}
          </div>);})}
        </div>
      </div>
      <div style={{display:"flex",gap:6,marginBottom:18,borderBottom:"1px solid #161b22"}}>
        {["checklist","details","audit"].map(t=><button key={t} onClick={()=>setTab(t)} style={{padding:"8px 18px",background:"transparent",border:"none",cursor:"pointer",fontSize:12,fontWeight:600,color:tab===t?"#e6edf3":"#6e7681",borderBottom:tab===t?"2px solid #d4a017":"2px solid transparent",marginBottom:-1,textTransform:"capitalize"}}>{t==="checklist"?`Checklist (${p.done}/${p.total})`:t==="audit"?"Audit Log":"Details"}</button>)}
      </div>
      {tab==="checklist"&&<div>
        <div style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,padding:"16px 20px",marginBottom:16}}>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10}}>
            <div style={{fontSize:13,color:"#e6edf3",fontWeight:600}}>Stage {c.stage}: {STAGE_LABELS[c.stage]}</div>
            <div style={{fontSize:12,color:p.allCriticalDone?"#3fb950":"#d4a017"}}>{p.allCriticalDone?"✓ All critical complete":`${p.criticalDone}/${p.criticalTotal} critical done`}</div>
          </div>
          <div style={{background:"#161b22",borderRadius:4,height:6,marginBottom:6}}><div style={{width:`${p.pct}%`,height:6,background:p.allCriticalDone?"#3fb950":STAGE_COLORS[c.stage],borderRadius:4,transition:"width 0.4s"}}/></div>
          <div style={{fontSize:11,color:"#6e7681"}}>{p.done} of {p.total} completed ({p.pct}%)</div>
        </div>
        <div style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,overflow:"hidden",marginBottom:16}}>
          {sc.map((ch,i)=>{const checked=checks[ch.id]||false;return(
            <div key={ch.id} onClick={()=>onToggleCheck(ch.id)} style={{display:"flex",alignItems:"center",gap:14,padding:"14px 18px",borderBottom:i<sc.length-1?"1px solid #161b22":"none",cursor:"pointer",background:checked?"#0d1f0d":"transparent",transition:"background 0.15s"}} onMouseEnter={e=>!checked&&(e.currentTarget.style.background="#161b22")} onMouseLeave={e=>!checked&&(e.currentTarget.style.background="transparent")}>
              <div style={{width:22,height:22,borderRadius:5,border:`2px solid ${checked?"#3fb950":"#30363d"}`,background:checked?"#3fb950":"transparent",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0,transition:"all 0.15s"}}>{checked&&<span style={{color:"#0d1117",fontSize:13,fontWeight:900}}>✓</span>}</div>
              <div style={{flex:1}}>
                <div style={{fontSize:13,color:checked?"#6e7681":"#e6edf3",textDecoration:checked?"line-through":"none"}}>{ch.label}</div>
                <div style={{fontSize:10,marginTop:2,color:ch.critical?(checked?"#3fb950":"#f85149"):"#484f58"}}>{ch.critical?(checked?"Critical — complete ✓":"Required to advance"):"Optional"}</div>
              </div>
            </div>
          );})}
        </div>
        {c.stage<8?(<div style={{background:"#0a0e15",border:`1px solid ${canAdvance?"#3fb950":"#161b22"}`,borderRadius:10,padding:"18px 20px",transition:"border 0.3s"}}>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}>
            <div>
              <div style={{fontSize:13,color:canAdvance?"#e6edf3":"#484f58",fontWeight:600,marginBottom:4}}>Advance to Stage {c.stage+1}: {STAGE_LABELS[c.stage+1]}</div>
              <div style={{fontSize:12,color:"#6e7681"}}>{canAdvance?"All critical checks complete — ready to progress.":`${p.criticalTotal-p.criticalDone} critical check(s) outstanding.`}</div>
            </div>
            <button onClick={canAdvance?onAdvance:undefined} style={{padding:"10px 28px",borderRadius:8,border:"none",cursor:canAdvance?"pointer":"not-allowed",background:canAdvance?"#166534":"#161b22",color:canAdvance?"#3fb950":"#484f58",fontSize:13,fontWeight:700,flexShrink:0,boxShadow:canAdvance?"0 0 16px #3fb95033":"none",transition:"all 0.2s"}}>{canAdvance?"Advance →":"Locked"}</button>
          </div>
        </div>):(<div style={{background:"#0a0e15",border:"1px solid #3fb95033",borderRadius:10,padding:"16px 20px",textAlign:"center",color:"#3fb950",fontSize:13}}>✓ Policy is In-Force — final stage reached</div>)}
      </div>}
      {tab==="details"&&<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
        <div style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,padding:"16px 18px"}}>
          <div style={{fontSize:11,letterSpacing:"0.15em",color:"#4a6fa5",textTransform:"uppercase",marginBottom:10}}>Policyholder</div>
          {[{k:"DOB",v:c.dob},{k:"Gender",v:c.gender},{k:"Smoker",v:c.smoker},{k:"NI Number",v:c.niNumber},{k:"Address",v:c.address},{k:"Contact",v:c.contact},{k:"Payment Freq",v:c.paymentFreq},{k:"Guarantee",v:c.guaranteePeriod}].filter(d=>d.v).map(d=>(
            <div key={d.k} style={{display:"flex",justifyContent:"space-between",padding:"5px 0",borderBottom:"1px solid #161b22",gap:10}}>
              <span style={{fontSize:11,color:"#6e7681",flexShrink:0}}>{d.k}</span><span style={{fontSize:11,color:"#e6edf3",textAlign:"right"}}>{d.v}</span>
            </div>
          ))}
        </div>
        <div style={{display:"flex",flexDirection:"column",gap:14}}>
          {buildExtraFields(c).length>0&&<div style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,padding:"16px 18px"}}>
            <div style={{fontSize:11,letterSpacing:"0.15em",color:"#d4a017",textTransform:"uppercase",marginBottom:10}}>Stage Data</div>
            {buildExtraFields(c).map(d=><div key={d.k} style={{display:"flex",justifyContent:"space-between",padding:"5px 0",borderBottom:"1px solid #161b22",gap:10}}><span style={{fontSize:11,color:"#6e7681",flexShrink:0}}>{d.k}</span><span style={{fontSize:11,color:"#e6edf3",textAlign:"right"}}>{d.v}</span></div>)}
          </div>}
          {c.notes&&<div style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,padding:"16px 18px"}}>
            <div style={{fontSize:11,color:"#8b949e",textTransform:"uppercase",marginBottom:8}}>Notes</div>
            <div style={{fontSize:12,color:"#94a3b8",lineHeight:1.6}}>{c.notes}</div>
          </div>}
        </div>
      </div>}
      {tab==="audit"&&<div style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,overflow:"hidden"}}>
        <div style={{padding:"12px 18px",borderBottom:"1px solid #161b22",fontSize:11,letterSpacing:"0.15em",textTransform:"uppercase",color:"#4a6fa5"}}>Immutable Audit Trail — FCA Compliant</div>
        {audit.length===0?<div style={{padding:"28px 18px",fontSize:13,color:"#484f58",textAlign:"center"}}>No audit events yet</div>
        :[...audit].reverse().map((e,i)=><div key={i} style={{padding:"12px 18px",borderBottom:"1px solid #0d1117",display:"flex",gap:14}}>
          <div style={{fontSize:10,color:"#484f58",fontFamily:"monospace",whiteSpace:"nowrap",paddingTop:2}}>{e.ts}</div>
          <div style={{flex:1}}><div style={{fontSize:12,color:"#e6edf3"}}>{e.action}</div><div style={{fontSize:10,color:"#6e7681",marginTop:2}}>{e.user}</div></div>
          <div style={{width:6,height:6,borderRadius:"50%",background:"#3fb950",marginTop:5,flexShrink:0}}/>
        </div>)}
      </div>}
    </div>
  </div>);
}

// ─── ACTIONS VIEW ─────────────────────────────────────────────────────────────
function ActionsView({allActions,onToggleCheck,onGoToCase}){
  const [filter,setFilter]=useState("all");
  const [sf,setSf]=useState(null);
  const displayed=allActions.filter(a=>filter==="critical"?a.critical:filter==="urgent"?a.urgent:true).filter(a=>sf?a.stage===sf:true);
  const byStage={};
  displayed.forEach(a=>{if(!byStage[a.stage])byStage[a.stage]=[];byStage[a.stage].push(a);});
  return(<div>
    <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:14,marginBottom:22}}>
      {[{label:"Total Outstanding",value:allActions.length,color:"#4a6fa5"},{label:"Critical (block stage)",value:allActions.filter(a=>a.critical).length,color:"#f85149"},{label:"On Urgent Cases",value:allActions.filter(a=>a.urgent).length,color:"#d4a017"}].map(s=>(
        <div key={s.label} style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,padding:"16px 18px"}}>
          <div style={{fontSize:11,color:"#6e7681",textTransform:"uppercase",letterSpacing:"0.1em",marginBottom:6}}>{s.label}</div>
          <div style={{fontSize:28,fontWeight:700,color:s.color}}>{s.value}</div>
        </div>
      ))}
    </div>
    <div style={{display:"flex",gap:8,marginBottom:18,flexWrap:"wrap"}}>
      {["all","critical","urgent"].map(f=><FilterBtn key={f} active={filter===f} onClick={()=>setFilter(f)} label={f.charAt(0).toUpperCase()+f.slice(1)} color={f==="critical"?"#f85149":f==="urgent"?"#d4a017":"#4a6fa5"} />)}
      <div style={{width:1,background:"#161b22",margin:"0 4px"}}/>
      {STAGES.map(s=>{const cnt=allActions.filter(a=>a.stage===s.n).length;if(!cnt)return null;return <FilterBtn key={s.n} active={sf===s.n} onClick={()=>setSf(sf===s.n?null:s.n)} label={`${s.label} (${cnt})`} color={STAGE_COLORS[s.n]} />;})}
    </div>
    {Object.keys(byStage).sort().map(stage=>(
      <div key={stage} style={{marginBottom:20}}>
        <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:10}}>
          <div style={{width:8,height:8,borderRadius:"50%",background:STAGE_COLORS[stage]}}/>
          <div style={{fontSize:11,letterSpacing:"0.15em",textTransform:"uppercase",color:STAGE_COLORS[stage],fontWeight:700}}>Stage {stage}: {STAGE_LABELS[stage]} — {byStage[stage].length} action{byStage[stage].length!==1?"s":""}</div>
        </div>
        <div style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,overflow:"hidden"}}>
          {byStage[stage].map((action,i)=>(
            <div key={`${action.caseId}-${action.checkId}`} style={{display:"flex",alignItems:"center",gap:14,padding:"13px 18px",borderBottom:i<byStage[stage].length-1?"1px solid #161b22":"none"}}>
              <div onClick={()=>onToggleCheck(action.caseId,action.checkId)} style={{width:20,height:20,borderRadius:4,border:"2px solid #30363d",background:"transparent",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0,cursor:"pointer"}}/>
              <div style={{flex:1,minWidth:0}}>
                <div style={{fontSize:13,color:"#e6edf3"}}>{action.label}</div>
                <div style={{fontSize:11,color:"#6e7681",marginTop:2}}><span style={{color:"#58a6ff",fontFamily:"monospace"}}>{action.caseId}</span> — {action.caseName} — {action.ifa} — {action.fund}</div>
              </div>
              <div style={{display:"flex",gap:6,alignItems:"center",flexShrink:0}}>
                {action.critical&&<span style={{fontSize:9,background:"#f8514922",border:"1px solid #f85149",color:"#f85149",borderRadius:3,padding:"1px 5px"}}>CRITICAL</span>}
                {action.urgent&&<span style={{fontSize:9,background:"#d4a01722",border:"1px solid #d4a017",color:"#d4a017",borderRadius:3,padding:"1px 5px"}}>URGENT</span>}
                <button onClick={()=>onGoToCase(action.caseId)} style={{background:"transparent",border:"1px solid #30363d",color:"#6e7681",borderRadius:5,padding:"3px 10px",fontSize:11,cursor:"pointer"}}>Open →</button>
              </div>
            </div>
          ))}
        </div>
      </div>
    ))}
    {displayed.length===0&&<div style={{textAlign:"center",padding:"60px 0",color:"#484f58",fontSize:14}}><div style={{fontSize:36,marginBottom:12}}>✓</div>No outstanding actions</div>}
  </div>);
}

// ─── IFA LIST ─────────────────────────────────────────────────────────────────
function IFAList({ifas,cases,onSelect}){
  const [filter,setFilter]=useState("all");
  const displayed=ifas.filter(i=>filter==="all"?true:i.status.toLowerCase()===filter);
  const totalPremium=ifas.reduce((s,i)=>s+(parseInt(i.totalPremium.replace(/[^0-9]/g,""))||0),0);
  const totalComm=ifas.reduce((s,i)=>s+(parseInt(i.commissionPaid.replace(/[^0-9]/g,""))||0),0);
  const statuses=["all","Active","Onboarding","Suspended"];
  const statusColor={Active:"#3fb950",Onboarding:"#388bfd",Suspended:"#f85149"};

  const reviewOverdue=(ifa)=>{
    if(!ifa.reviewDueDate||ifa.status!=="Active") return false;
    const [d,m,y]=ifa.reviewDueDate.split("/");
    return new Date(`${y}-${m}-${d}`)<new Date();
  };

  return(<div>
    <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14,marginBottom:24}}>
      {[{label:"Total IFA Partners",value:ifas.length,color:"#4a6fa5"},{label:"Total Premium Placed",value:"£"+totalPremium.toLocaleString(),color:"#d4a017"},{label:"Commission Paid",value:"£"+totalComm.toLocaleString(),color:"#3fb950"},{label:"Reviews Overdue",value:ifas.filter(reviewOverdue).length,color:"#f85149"}].map(s=>(
        <div key={s.label} style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,padding:"16px 18px"}}>
          <div style={{fontSize:11,color:"#6e7681",textTransform:"uppercase",letterSpacing:"0.1em",marginBottom:6}}>{s.label}</div>
          <div style={{fontSize:22,fontWeight:700,color:s.color}}>{s.value}</div>
        </div>
      ))}
    </div>
    <div style={{display:"flex",gap:8,marginBottom:16}}>
      {statuses.map(f=><FilterBtn key={f} active={filter===f} onClick={()=>setFilter(f)} label={f==="all"?`All (${ifas.length})`:f+` (${ifas.filter(i=>i.status===f).length})`} color={f==="all"?"#4a6fa5":statusColor[f]||"#4a6fa5"} />)}
    </div>
    <div style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,overflow:"hidden"}}>
      <table style={{width:"100%",borderCollapse:"collapse"}}>
        <thead><tr style={{borderBottom:"1px solid #161b22"}}>
          {["Firm","Type","FCA No.","Status","Cases","Completed","Incomplete","Commission Rate","Total Paid","Review Due","RM",""].map(h=><th key={h} style={{padding:"10px 12px",textAlign:"left",fontSize:10,letterSpacing:"0.1em",textTransform:"uppercase",color:"#4a6fa5",fontWeight:600,whiteSpace:"nowrap"}}>{h}</th>)}
        </tr></thead>
        <tbody>{displayed.map((ifa,i)=>{
          const overdue=reviewOverdue(ifa);
          return(<tr key={ifa.id} onClick={()=>onSelect(ifa.id)} style={{borderBottom:"1px solid #0d1117",cursor:"pointer",background:i%2===0?"transparent":"#0b0f16"}} onMouseEnter={e=>e.currentTarget.style.background="#161b22"} onMouseLeave={e=>e.currentTarget.style.background=i%2===0?"transparent":"#0b0f16"}>
            <td style={{padding:"12px 12px"}}><div style={{fontSize:13,color:"#e6edf3",fontWeight:600}}>{ifa.firm}</div></td>
            <td style={{padding:"12px 12px",fontSize:11,color:"#6e7681"}}>{ifa.type}</td>
            <td style={{padding:"12px 12px",fontSize:11,color:"#8b949e",fontFamily:"monospace"}}>{ifa.fcaNumber}</td>
            <td style={{padding:"12px 12px"}}><span style={{fontSize:10,background:(statusColor[ifa.status]||"#374151")+"22",border:`1px solid ${(statusColor[ifa.status]||"#374151")}66`,color:statusColor[ifa.status]||"#374151",borderRadius:4,padding:"2px 7px"}}>{ifa.status}</span></td>
            <td style={{padding:"12px 12px",fontSize:13,color:"#e6edf3",textAlign:"center"}}>{ifa.totalCasesSubmitted}</td>
            <td style={{padding:"12px 12px",fontSize:12,color:"#3fb950",textAlign:"center"}}>{ifa.casesCompleted}</td>
            <td style={{padding:"12px 12px",fontSize:12,color:ifa.casesIncomplete>0?"#f85149":"#6e7681",textAlign:"center"}}>{ifa.casesIncomplete}</td>
            <td style={{padding:"12px 12px",fontSize:12,color:"#d4a017"}}>{ifa.initialCommission}%</td>
            <td style={{padding:"12px 12px",fontSize:12,color:"#d4a017"}}>{ifa.commissionPaid}</td>
            <td style={{padding:"12px 12px",fontSize:11,color:overdue?"#f85149":"#6e7681"}}>{ifa.reviewDueDate||"—"}{overdue&&" ⚠"}</td>
            <td style={{padding:"12px 12px",fontSize:11,color:"#6e7681"}}>{ifa.relationshipManager}</td>
            <td style={{padding:"12px 12px",fontSize:12,color:"#4a6fa5"}}>→</td>
          </tr>);
        })}</tbody>
      </table>
    </div>
  </div>);
}

// ─── IFA DETAIL ───────────────────────────────────────────────────────────────
function IFADetail({ifa,cases,onToggleCheck,showToast}){
  const [tab,setTab]=useState("overview");
  const obChecks=ONBOARDING_STAGES;
  const obDone=obChecks.filter(c=>ifa.onboardingChecks[c.id]).length;
  const obPct=Math.round((obDone/obChecks.length)*100);
  const statusColor={Active:"#3fb950",Onboarding:"#388bfd",Suspended:"#f85149"};
  const sc=statusColor[ifa.status]||"#374151";

  const reviewOverdue=ifa.reviewDueDate&&ifa.status==="Active"&&(()=>{const[d,m,y]=ifa.reviewDueDate.split("/");return new Date(`${y}-${m}-${d}`)<new Date();})();

  return(<div>
    <style>{`@keyframes fadeUp{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}`}</style>
    <div style={{animation:"fadeUp 0.2s ease"}}>

      {/* Header cards */}
      <div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:14,marginBottom:20}}>
        {[{l:"Status",v:ifa.status,c:sc},{l:"Cases Submitted",v:ifa.totalCasesSubmitted,c:"#e6edf3"},{l:"Completed",v:ifa.casesCompleted,c:"#3fb950"},{l:"Incomplete",v:ifa.casesIncomplete,c:ifa.casesIncomplete>0?"#f85149":"#6e7681"},{l:"Commission Paid",v:ifa.commissionPaid,c:"#d4a017"}].map(item=>(
          <div key={item.l} style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:8,padding:"14px 16px"}}>
            <div style={{fontSize:10,letterSpacing:"0.15em",color:"#4a6fa5",textTransform:"uppercase",marginBottom:4}}>{item.l}</div>
            <div style={{fontSize:18,color:item.c,fontWeight:700}}>{item.v}</div>
          </div>
        ))}
      </div>

      {/* Alerts */}
      {reviewOverdue&&<div style={{background:"#2a1a00",border:"1px solid #d4a017",borderRadius:8,padding:"12px 16px",marginBottom:16,fontSize:12,color:"#d4a017"}}>⚠ Annual review overdue — due {ifa.reviewDueDate}. KYC/AML refresh required. Escalated to Compliance.</div>}
      {ifa.status==="Suspended"&&<div style={{background:"#2a0000",border:"1px solid #f85149",borderRadius:8,padding:"12px 16px",marginBottom:16,fontSize:12,color:"#f85149"}}>🚫 IFA SUSPENDED — Do not accept new cases. Compliance investigation in progress.</div>}

      {/* Tabs */}
      <div style={{display:"flex",gap:6,marginBottom:18,borderBottom:"1px solid #161b22"}}>
        {["overview","onboarding","kyc-aml","cases","commission"].map(t=>(
          <button key={t} onClick={()=>setTab(t)} style={{padding:"8px 16px",background:"transparent",border:"none",cursor:"pointer",fontSize:12,fontWeight:600,color:tab===t?"#e6edf3":"#6e7681",borderBottom:tab===t?"2px solid #d4a017":"2px solid transparent",marginBottom:-1,textTransform:"capitalize",whiteSpace:"nowrap"}}>
            {t==="kyc-aml"?"KYC / AML":t==="onboarding"?`Onboarding (${obDone}/${obChecks.length})`:t.charAt(0).toUpperCase()+t.slice(1)}
          </button>
        ))}
      </div>

      {/* OVERVIEW */}
      {tab==="overview"&&<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
        <div style={{display:"flex",flexDirection:"column",gap:14}}>
          <div style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,padding:"16px 18px"}}>
            <div style={{fontSize:11,letterSpacing:"0.15em",color:"#4a6fa5",textTransform:"uppercase",marginBottom:10}}>Firm Details</div>
            {[{k:"Firm",v:ifa.firm},{k:"Type",v:ifa.type},{k:"FCA Number",v:ifa.fcaNumber},{k:"Unipass ID",v:ifa.unipaussId||"Not yet assigned"},{k:"Address",v:ifa.address},{k:"Contact",v:ifa.contact},{k:"Relationship Manager",v:ifa.relationshipManager},{k:"Last Contact",v:ifa.lastContact},{k:"Preferred Contact",v:ifa.preferredContact}].map(d=>(
              <div key={d.k} style={{display:"flex",justifyContent:"space-between",padding:"5px 0",borderBottom:"1px solid #161b22",gap:10}}>
                <span style={{fontSize:11,color:"#6e7681",flexShrink:0}}>{d.k}</span><span style={{fontSize:11,color:"#e6edf3",textAlign:"right"}}>{d.v}</span>
              </div>
            ))}
          </div>
        </div>
        <div style={{display:"flex",flexDirection:"column",gap:14}}>
          <div style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,padding:"16px 18px"}}>
            <div style={{fontSize:11,letterSpacing:"0.15em",color:"#d4a017",textTransform:"uppercase",marginBottom:10}}>Commission Structure</div>
            {[{k:"Commission Type",v:ifa.commissionType},{k:"Initial Rate",v:ifa.initialCommission+"%"},{k:"Trail Commission",v:ifa.trailCommission+"%"},{k:"Payment Terms",v:ifa.paymentTerms},{k:"Total Premium Placed",v:ifa.totalPremium},{k:"Total Commission Paid",v:ifa.commissionPaid}].map(d=>(
              <div key={d.k} style={{display:"flex",justifyContent:"space-between",padding:"5px 0",borderBottom:"1px solid #161b22",gap:10}}>
                <span style={{fontSize:11,color:"#6e7681",flexShrink:0}}>{d.k}</span><span style={{fontSize:11,color:"#e6edf3",textAlign:"right"}}>{d.v}</span>
              </div>
            ))}
          </div>
          <div style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,padding:"16px 18px"}}>
            <div style={{fontSize:11,letterSpacing:"0.15em",color:"#8b949e",textTransform:"uppercase",marginBottom:8}}>Notes</div>
            <div style={{fontSize:12,color:"#94a3b8",lineHeight:1.6}}>{ifa.notes}</div>
          </div>
          <div style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,padding:"16px 18px"}}>
            <div style={{fontSize:11,letterSpacing:"0.15em",color:"#8b949e",textTransform:"uppercase",marginBottom:10}}>Submission Quality</div>
            {[{label:"Total Submitted",value:ifa.totalCasesSubmitted,color:"#e6edf3"},{label:"Completed Successfully",value:ifa.casesCompleted,color:"#3fb950"},{label:"Currently Pending",value:ifa.casesPending,color:"#388bfd"},{label:"Incomplete / Returned",value:ifa.casesIncomplete,color:ifa.casesIncomplete>0?"#f85149":"#6e7681"}].map(item=>(
              <div key={item.label} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"7px 0",borderBottom:"1px solid #161b22"}}>
                <span style={{fontSize:12,color:"#8b949e"}}>{item.label}</span>
                <span style={{fontSize:14,color:item.color,fontWeight:700}}>{item.value}</span>
              </div>
            ))}
            {ifa.totalCasesSubmitted>0&&<div style={{marginTop:10}}>
              <div style={{fontSize:10,color:"#6e7681",marginBottom:4}}>Completion rate</div>
              <div style={{background:"#161b22",borderRadius:4,height:6}}><div style={{width:`${Math.round((ifa.casesCompleted/ifa.totalCasesSubmitted)*100)}%`,height:6,background:"#3fb950",borderRadius:4}}/></div>
              <div style={{fontSize:10,color:"#3fb950",marginTop:3}}>{Math.round((ifa.casesCompleted/ifa.totalCasesSubmitted)*100)}%</div>
            </div>}
          </div>
        </div>
      </div>}

      {/* ONBOARDING CHECKLIST */}
      {tab==="onboarding"&&<div>
        <div style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,padding:"16px 20px",marginBottom:16}}>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10}}>
            <div style={{fontSize:13,color:"#e6edf3",fontWeight:600}}>Vendor Onboarding Progress</div>
            <div style={{fontSize:12,color:obPct===100?"#3fb950":"#d4a017"}}>{obDone}/{obChecks.length} stages complete</div>
          </div>
          <div style={{background:"#161b22",borderRadius:4,height:6,marginBottom:6}}><div style={{width:`${obPct}%`,height:6,background:obPct===100?"#3fb950":"#388bfd",borderRadius:4,transition:"width 0.4s"}}/></div>
          <div style={{fontSize:11,color:"#6e7681"}}>{obPct}% complete{obPct===100?" — fully onboarded":""}</div>
        </div>
        <div style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,overflow:"hidden"}}>
          {obChecks.map((ch,i)=>{const checked=ifa.onboardingChecks[ch.id]||false;return(
            <div key={ch.id} onClick={()=>onToggleCheck(ch.id)} style={{display:"flex",alignItems:"center",gap:14,padding:"14px 18px",borderBottom:i<obChecks.length-1?"1px solid #161b22":"none",cursor:"pointer",background:checked?"#0d1f0d":"transparent",transition:"background 0.15s"}} onMouseEnter={e=>!checked&&(e.currentTarget.style.background="#161b22")} onMouseLeave={e=>!checked&&(e.currentTarget.style.background="transparent")}>
              <div style={{width:22,height:22,borderRadius:5,border:`2px solid ${checked?"#3fb950":"#30363d"}`,background:checked?"#3fb950":"transparent",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0,transition:"all 0.15s"}}>{checked&&<span style={{color:"#0d1117",fontSize:13,fontWeight:900}}>✓</span>}</div>
              <div style={{flex:1}}>
                <div style={{fontSize:13,color:checked?"#6e7681":"#e6edf3",textDecoration:checked?"line-through":"none"}}>{ch.label}</div>
              </div>
              <div style={{fontSize:11,color:checked?"#3fb950":"#484f58"}}>{checked?"Complete":"Pending"}</div>
            </div>
          );})}
        </div>
      </div>}

      {/* KYC / AML */}
      {tab==="kyc-aml"&&<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
        <div style={{display:"flex",flexDirection:"column",gap:14}}>
          <div style={{background:"#0a0e15",border:`1px solid ${ifa.sanctions.screened?"#3fb95033":"#f8514933"}`,borderRadius:10,padding:"16px 18px"}}>
            <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}>
              <div style={{fontSize:11,letterSpacing:"0.15em",color:"#4a6fa5",textTransform:"uppercase"}}>Sanctions Screening</div>
              <span style={{fontSize:10,background:ifa.sanctions.screened?"#3fb95022":"#f8514922",border:`1px solid ${ifa.sanctions.screened?"#3fb950":"#f85149"}`,color:ifa.sanctions.screened?"#3fb950":"#f85149",borderRadius:4,padding:"2px 7px"}}>{ifa.sanctions.screened?"Screened":"Pending"}</span>
            </div>
            {[{k:"Result",v:ifa.sanctions.result},{k:"Screening Provider",v:ifa.sanctions.provider},{k:"Date Screened",v:ifa.sanctions.screenedDate||"Not yet"},{k:"Next Review",v:ifa.sanctions.nextReview||"TBC"}].map(d=>(
              <div key={d.k} style={{display:"flex",justifyContent:"space-between",padding:"5px 0",borderBottom:"1px solid #161b22",gap:10}}>
                <span style={{fontSize:11,color:"#6e7681",flexShrink:0}}>{d.k}</span><span style={{fontSize:11,color:d.v?.includes("REVIEW")||d.v?.includes("progress")?"#f85149":"#e6edf3",textAlign:"right"}}>{d.v}</span>
              </div>
            ))}
          </div>
          <div style={{background:"#0a0e15",border:`1px solid ${ifa.pep.checked?"#3fb95033":"#f8514933"}`,borderRadius:10,padding:"16px 18px"}}>
            <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}>
              <div style={{fontSize:11,letterSpacing:"0.15em",color:"#4a6fa5",textTransform:"uppercase"}}>PEP / RCA Check</div>
              <span style={{fontSize:10,background:ifa.pep.checked?"#3fb95022":"#f8514922",border:`1px solid ${ifa.pep.checked?"#3fb950":"#f85149"}`,color:ifa.pep.checked?"#3fb950":"#f85149",borderRadius:4,padding:"2px 7px"}}>{ifa.pep.checked?"Completed":"Pending"}</span>
            </div>
            {[{k:"Result",v:ifa.pep.result},{k:"Date Checked",v:ifa.pep.checkedDate||"Not yet"}].map(d=>(
              <div key={d.k} style={{display:"flex",justifyContent:"space-between",padding:"5px 0",borderBottom:"1px solid #161b22",gap:10}}>
                <span style={{fontSize:11,color:"#6e7681",flexShrink:0}}>{d.k}</span><span style={{fontSize:11,color:"#e6edf3",textAlign:"right"}}>{d.v}</span>
              </div>
            ))}
          </div>
        </div>
        <div style={{display:"flex",flexDirection:"column",gap:14}}>
          <div style={{background:"#0a0e15",border:`1px solid ${ifa.aml.verified?"#3fb95033":"#f8514933"}`,borderRadius:10,padding:"16px 18px"}}>
            <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}>
              <div style={{fontSize:11,letterSpacing:"0.15em",color:"#4a6fa5",textTransform:"uppercase"}}>AML Verification</div>
              <span style={{fontSize:10,background:ifa.aml.verified?"#3fb95022":"#f8514922",border:`1px solid ${ifa.aml.verified?"#3fb950":"#f85149"}`,color:ifa.aml.verified?"#3fb950":"#f85149",borderRadius:4,padding:"2px 7px"}}>{ifa.aml.verified?"Verified":"Pending"}</span>
            </div>
            {[{k:"Verification Method",v:ifa.aml.method},{k:"Date Verified",v:ifa.aml.verifiedDate||"Not yet"},{k:"Next Review",v:ifa.aml.nextReview||"TBC"}].map(d=>(
              <div key={d.k} style={{display:"flex",justifyContent:"space-between",padding:"5px 0",borderBottom:"1px solid #161b22",gap:10}}>
                <span style={{fontSize:11,color:"#6e7681",flexShrink:0}}>{d.k}</span><span style={{fontSize:11,color:"#e6edf3",textAlign:"right"}}>{d.v}</span>
              </div>
            ))}
            <div style={{marginTop:12}}>
              <div style={{fontSize:10,color:"#6e7681",marginBottom:6}}>Documents Obtained</div>
              {ifa.aml.documents.map(doc=><div key={doc} style={{fontSize:11,color:"#8b949e",padding:"3px 0",borderBottom:"1px solid #161b22"}}>⬡ {doc}</div>)}
            </div>
          </div>
          <div style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,padding:"16px 18px"}}>
            <div style={{fontSize:11,letterSpacing:"0.15em",color:"#8b949e",textTransform:"uppercase",marginBottom:10}}>FCA Register Check</div>
            {[{k:"FCA Number",v:ifa.fcaNumber},{k:"Verified",v:ifa.onboardingChecks.fca_check?"Yes — FCA Register confirmed":"Not yet verified"},{k:"Agency Agreement",v:ifa.onboardingChecks.agency_agreement?"Signed":"Not yet signed"}].map(d=>(
              <div key={d.k} style={{display:"flex",justifyContent:"space-between",padding:"5px 0",borderBottom:"1px solid #161b22",gap:10}}>
                <span style={{fontSize:11,color:"#6e7681",flexShrink:0}}>{d.k}</span><span style={{fontSize:11,color:d.v?.includes("Not")?"#f85149":"#e6edf3",textAlign:"right"}}>{d.v}</span>
              </div>
            ))}
          </div>
        </div>
      </div>}

      {/* CASES */}
      {tab==="cases"&&<div>
        {cases.length===0?<div style={{textAlign:"center",padding:"60px 0",color:"#484f58",fontSize:14}}><div style={{fontSize:36,marginBottom:12}}>⬜</div>No active cases for this IFA</div>
        :<div style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,overflow:"hidden"}}>
          <table style={{width:"100%",borderCollapse:"collapse"}}>
            <thead><tr style={{borderBottom:"1px solid #161b22"}}>{["Case ID","Policyholder","Fund","Stage","Status"].map(h=><th key={h} style={{padding:"10px 14px",textAlign:"left",fontSize:10,letterSpacing:"0.1em",textTransform:"uppercase",color:"#4a6fa5",fontWeight:600}}>{h}</th>)}</tr></thead>
            <tbody>{cases.map((c,i)=>(
              <tr key={c.id} style={{borderBottom:"1px solid #0d1117",background:i%2===0?"transparent":"#0b0f16"}}>
                <td style={{padding:"11px 14px",fontSize:11,color:"#58a6ff",fontFamily:"monospace"}}>{c.id}</td>
                <td style={{padding:"11px 14px",fontSize:13,color:"#e6edf3"}}>{c.name}</td>
                <td style={{padding:"11px 14px",fontSize:13,color:"#d4a017"}}>{c.fund}</td>
                <td style={{padding:"11px 14px"}}><StageBadge stage={c.stage}/></td>
                <td style={{padding:"11px 14px",fontSize:11,color:"#8b949e"}}>{STAGE_LABELS[c.stage]}</td>
              </tr>
            ))}</tbody>
          </table>
        </div>}
      </div>}

      {/* COMMISSION */}
      {tab==="commission"&&<div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginBottom:16}}>
          <div style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,padding:"16px 18px"}}>
            <div style={{fontSize:11,letterSpacing:"0.15em",color:"#d4a017",textTransform:"uppercase",marginBottom:10}}>Commission Terms</div>
            {[{k:"Commission Type",v:ifa.commissionType},{k:"Initial Rate",v:ifa.initialCommission+"%"},{k:"Trail Rate",v:ifa.trailCommission+"%"},{k:"Payment Terms",v:ifa.paymentTerms},{k:"Total Premium Placed",v:ifa.totalPremium},{k:"Total Commission Paid",v:ifa.commissionPaid}].map(d=>(
              <div key={d.k} style={{display:"flex",justifyContent:"space-between",padding:"6px 0",borderBottom:"1px solid #161b22",gap:10}}>
                <span style={{fontSize:11,color:"#6e7681",flexShrink:0}}>{d.k}</span><span style={{fontSize:12,color:"#e6edf3",fontWeight:600,textAlign:"right"}}>{d.v}</span>
              </div>
            ))}
          </div>
          <div style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,padding:"16px 18px"}}>
            <div style={{fontSize:11,letterSpacing:"0.15em",color:"#d4a017",textTransform:"uppercase",marginBottom:10}}>Recent Payments</div>
            {ifa.commissionHistory.length===0?<div style={{fontSize:12,color:"#484f58",textAlign:"center",padding:"20px 0"}}>No payments yet</div>
            :ifa.commissionHistory.map((p,i)=>(
              <div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"8px 0",borderBottom:"1px solid #161b22"}}>
                <div><div style={{fontSize:12,color:"#e6edf3",fontWeight:600}}>{p.amount}</div><div style={{fontSize:10,color:"#6e7681",marginTop:1}}>{p.cases} case{p.cases!==1?"s":""} · {p.date}</div></div>
                <span style={{fontSize:9,background:"#3fb95022",border:"1px solid #3fb95066",color:"#3fb950",borderRadius:3,padding:"2px 6px"}}>Paid</span>
              </div>
            ))}
          </div>
        </div>
        <div style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,padding:"16px 18px"}}>
          <div style={{fontSize:11,letterSpacing:"0.15em",color:"#8b949e",textTransform:"uppercase",marginBottom:10}}>FCA Disclosure Requirements</div>
          {["Commission amount disclosed on all policy schedules","Remuneration basis confirmed with policyholder","IDD (Insurance Distribution Directive) disclosure complete","Any referral arrangements documented and disclosed"].map(r=>(
            <div key={r} style={{fontSize:12,color:"#8b949e",padding:"5px 0",borderBottom:"1px solid #161b22",paddingLeft:8,borderLeft:"2px solid #d4a01744"}}>{r}</div>
          ))}
        </div>
      </div>}
    </div>
  </div>);
}

// ─── WORKFLOW REFERENCE ───────────────────────────────────────────────────────
function WorkflowRef(){
  const [active,setActive]=useState(null);
  const stages=[
    {id:1,label:"Enquiry & Quote",color:"#388bfd",states:["New Enquiry","Quote Requested","Quote Generated","Sent to IFA"],data:["DOB, gender, smoker status","Fund value & pension type","Annuity type","IFA FCA & Unipass ID","Postcode"],integrations:["Unipass / Origo","Pricing engine"],rules:["Enhanced triage required","Joint life — collect partner details","Quote valid 5 days"]},
    {id:2,label:"Underwriting",color:"#b45309",states:["Awaiting Medical","GP Report Requested","Evidence Received","UW Decision","Chief UW Referral"],data:["ICD-10 conditions","Medications","GP practice","iGPR / Morgan Ash ref"],integrations:["iGPR API","Morgan Ash MARS","UW rules engine"],rules:["Refer: 2+ conditions","Art.9 GDPR isolation","SLA: 10 working days"]},
    {id:3,label:"Repricing",color:"#d4a017",states:["Triggered","Calculated","IFA Notified","IFA Accepted","Lapsed"],data:["Reason code","New rate","Validity window","IFA timestamp"],integrations:["Pricing engine","Mailock"],rules:["Validity: 5 days","Auto-lapse if no IFA response","FCA audit log required"]},
    {id:4,label:"Reinsurer",color:"#0f766e",states:["Pack Prepared","Sent","Awaiting Decision","Accepted","Counter-offer"],data:["Medical bundle","Treaty ref","Sum reinsured"],integrations:["Reinsurer portal / SFTP"],rules:["Facultative: fund >£200k","30-day SLA","Counter-offer → Chief UW"]},
    {id:5,label:"Fund Transfer",color:"#1d4ed8",states:["Requested","Awaiting","Partial","Full Receipt","Reconciled"],data:["Ceding provider","Expected & received","Origo ref"],integrations:["Origo Options","Bank reconciliation"],rules:["Tolerance ±£50","Partial: hold policy issue","30-day lapse warning"]},
    {id:6,label:"Policy Issue",color:"#166534",states:["Pre-issue Checks","Docs Generated","Sent to PH","Sent to IFA","Live"],data:["Policy number","Commencement","First payment","Cooling-off date"],integrations:["DocuSign","IFA back-office","Payment engine"],rules:["FCA: schedule + IPID + welcome letter","30-day cooling off","Consumer Duty confirmation"]},
    {id:7,label:"In-Force",color:"#374151",states:["Live","Payment Query","Death Claim","Survivor Pension","Ceased"],data:["Payment status","Beneficiary details","Death notification"],integrations:["BACS","DWP Tell Us Once","Annual statements"],rules:["Joint life: survivor pension on death","Guarantee: pay to estate","Annual statement FCA required"]},
  ];
  const s=stages.find(x=>x.id===active);
  return(<div>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(200px,1fr))",gap:10,marginBottom:20}}>
      {stages.map(st=>(
        <div key={st.id} onClick={()=>setActive(active===st.id?null:st.id)} style={{background:active===st.id?"#161b22":"#0a0e15",border:`1px solid ${active===st.id?st.color:"#161b22"}`,borderRadius:8,padding:"14px 16px",cursor:"pointer"}}>
          <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:8}}>
            <div style={{width:8,height:8,borderRadius:"50%",background:st.color}}/><span style={{fontSize:11,fontWeight:700,color:st.color}}>0{st.id}. {st.label}</span>
          </div>
          <div style={{display:"flex",flexWrap:"wrap",gap:3}}>
            {st.states.slice(0,3).map(state=><span key={state} style={{fontSize:9,background:"#0d1117",color:"#6e7681",padding:"1px 5px",borderRadius:3,border:"1px solid #161b22"}}>{state}</span>)}
            {st.states.length>3&&<span style={{fontSize:9,color:"#4a6fa5"}}>+{st.states.length-3}</span>}
          </div>
        </div>
      ))}
    </div>
    {s&&<div style={{background:"#0a0e15",border:`1px solid ${s.color}44`,borderRadius:10,padding:22}}>
      <div style={{fontSize:15,fontWeight:700,color:"#e6edf3",marginBottom:16,display:"flex",gap:10,alignItems:"center"}}><div style={{width:10,height:10,borderRadius:"50%",background:s.color}}/>{s.label}</div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:16}}>
        {[{title:"States",color:s.color,items:s.states},{title:"Data Required",color:"#d4a017",items:s.data},{title:"Integrations",color:"#3fb950",items:s.integrations},{title:"Rules",color:"#f85149",items:s.rules}].map(sec=>(
          <div key={sec.title}>
            <div style={{fontSize:10,letterSpacing:"0.15em",textTransform:"uppercase",color:sec.color,marginBottom:8,fontWeight:700}}>{sec.title}</div>
            {sec.items.map(item=><div key={item} style={{fontSize:12,color:"#8b949e",padding:"4px 0",borderBottom:"1px solid #161b22"}}>{item}</div>)}
          </div>
        ))}
      </div>
    </div>}
  </div>);
}

// ─── INTEGRATIONS ─────────────────────────────────────────────────────────────
function IntegrationsView(){
  const items=[{name:"iGPR",category:"Medical",status:"Pending Contract",effort:"2–4 weeks",desc:"GP report requests and structured medical evidence retrieval"},{name:"Morgan Ash MARS",category:"Medical / Vulnerability",status:"Pending Contract",effort:"3–5 weeks",desc:"Vulnerability assessments and complex medical data flows"},{name:"Unipass / Origo",category:"IFA Identity",status:"Accreditation Required",effort:"4–6 weeks",desc:"IFA authentication, authorisation and FCA number verification"},{name:"Origo Options",category:"Fund Transfer",status:"Accreditation Required",effort:"4–8 weeks",desc:"Pension transfer tracking across the UK provider network"},{name:"Munich Re",category:"Reinsurer",status:"Commercial Negotiation",effort:"1–3 months",desc:"Facultative and treaty submission for large and impaired cases"},{name:"RGA UK",category:"Reinsurer",status:"Commercial Negotiation",effort:"1–3 months",desc:"Secondary reinsurance partner — counter-offer and specialist cases"},{name:"DocuSign",category:"e-Signature",status:"Ready to Integrate",effort:"1–2 weeks",desc:"Policy document signing and IFA acceptance workflows"},{name:"Mailock",category:"Secure Messaging",status:"Ready to Integrate",effort:"1–2 weeks",desc:"FCA-compliant secure email for IFA and policyholder comms"},{name:"BACS / Faster Payments",category:"Payments",status:"Banking Partner Required",effort:"6–10 weeks",desc:"Monthly annuity payment runs — requires sponsor bank"},{name:"ComplyAdvantage",category:"Sanctions / AML",status:"Ready to Integrate",effort:"1–2 weeks",desc:"Real-time sanctions screening, PEP checks and AML monitoring for IFA onboarding"},{name:"LexisNexis",category:"KYC / AML",status:"Ready to Integrate",effort:"2–3 weeks",desc:"Enhanced due diligence and identity verification for IFA firms"},{name:"DWP Tell Us Once",category:"Death Notification",status:"Future Phase",effort:"3–6 months",desc:"Automated death notifications to trigger in-force claim workflows"}];
  const sc={"Ready to Integrate":"#3fb950","Pending Contract":"#d4a017","Accreditation Required":"#388bfd","Commercial Negotiation":"#f85149","Banking Partner Required":"#b45309","Future Phase":"#374151"};
  return(<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:14}}>
    {items.map(item=>(
      <div key={item.name} style={{background:"#0a0e15",border:"1px solid #161b22",borderRadius:10,padding:"16px 18px"}}>
        <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:8}}>
          <div><div style={{fontSize:14,fontWeight:700,color:"#e6edf3"}}>{item.name}</div><div style={{fontSize:10,color:"#4a6fa5",marginTop:1}}>{item.category}</div></div>
          <div style={{fontSize:9,background:sc[item.status]+"22",border:`1px solid ${sc[item.status]}66`,color:sc[item.status],borderRadius:4,padding:"2px 7px",whiteSpace:"nowrap"}}>{item.status}</div>
        </div>
        <div style={{fontSize:12,color:"#8b949e",marginBottom:8,lineHeight:1.5}}>{item.desc}</div>
        <div style={{fontSize:11,color:"#6e7681"}}>Est. effort: <span style={{color:"#c9d1d9"}}>{item.effort}</span></div>
      </div>
    ))}
  </div>);
}

// ─── HELPERS ──────────────────────────────────────────────────────────────────
function StageBadge({stage}){
  const color=STAGE_COLORS[stage]||"#374151";
  return <span style={{background:color+"22",border:`1px solid ${color}55`,color:"#e6edf3",borderRadius:4,padding:"2px 8px",fontSize:10,whiteSpace:"nowrap"}}>{stage}. {STAGE_LABELS[stage]}</span>;
}
function FilterBtn({active,onClick,label,color}){
  return <button onClick={onClick} style={{padding:"5px 14px",borderRadius:5,border:`1px solid ${active?color:"#30363d"}`,background:active?color+"22":"transparent",color:active?color:"#6e7681",fontSize:12,cursor:"pointer"}}>{label}</button>;
}
function buildExtraFields(c){
  const f=[],add=(k,v)=>{if(v)f.push({k,v})};
  add("Conditions",c.conditions);add("Medications",c.medications);add("GP Practice",c.gp);add("iGPR Ref",c.igprRef);add("Morgan Ash Ref",c.morganAshRef);add("UW Decision",c.uwDecision);
  add("Reprice Reason",c.repriceReason);add("New Rate",c.newRate);add("Previous Rate",c.previousRate);add("Rate Change",c.rateChange);add("Validity Expires",c.validityExpiry);
  add("Reinsurer",c.reinsurer);add("Treaty Ref",c.treatyRef);add("Sum Reinsured",c.sumReinsured);add("Counter-offer",c.counterOffer);
  add("Ceding Provider",c.cedingProvider);add("Expected Transfer",c.expectedTransfer);add("Received",c.receivedAmount);add("Origo Ref",c.origoRef);add("Reconciled",c.reconciled);
  add("Policy Number",c.policyNumber);add("Commencement",c.commencementDate);add("First Payment",c.firstPaymentDate);add("Annual Income",c.annualIncome);add("Cooling Off Expires",c.coolingOffExpiry);add("IFA Commission",c.ifaCommission);
  add("Last Payment",c.lastPaymentDate);add("Next Payment",c.nextPaymentDate);
  return f;
}
